export { Web3Modal } from '../src/client.js'
export type { Web3ModalOptions } from '../src/client.js'
export { defaultWagmiConfig as defaultConfig } from '../src/utils/defaultWagmiCoreConfig.js'
export type { DefaultConfigOptions } from '../src/utils/defaultWagmiCoreConfig.js'
export { walletConnectProvider } from '../src/utils/provider.js'
