packages:
  - 'packages/adapters/*'
  - 'packages/appkit'
  - 'packages/common'
  - 'packages/ui'
  - 'packages/ui-new'
  - 'packages/core'
  - 'packages/appkit-utils'
  - 'packages/scaffold-ui'
  - 'packages/polyfills'
  - 'packages/wallet'
  - 'packages/siwe'
  - 'packages/siwx'
  - 'packages/cdn'
  - 'packages/experimental'
  - 'apps/*'
  - 'examples/*'
  - 'services/*'
