packages:
  - packages/adapters/*
  - packages/appkit
  - packages/common
  - packages/ui
  - packages/controllers
  - packages/core-legacy
  - packages/appkit-utils
  - packages/scaffold-ui
  - packages/polyfills
  - packages/wallet
  - packages/siwe
  - packages/siwx
  - packages/wallet-button
  - packages/cdn
  - packages/experimental
  - packages/cli
  - apps/*
  - examples/*
  - services/*
  - packages/ui-new
  - '!packages/appkit-new'
  - '!apps/gallery-new'
  - '!apps/laboratory-new'
onlyBuiltDependencies:
  - '@ampproject/remapping'
  - '@asamuzakjp/css-color'
  - '@babel/code-frame'
  - '@babel/generator'
  - '@babel/helper-string-parser'
  - '@babel/helper-validator-identifier'
  - '@babel/parser'
  - '@babel/runtime'
  - '@babel/template'
  - '@babel/traverse'
  - '@babel/types'
  - '@bcoe/v8-coverage'
  - '@changesets/apply-release-plan'
  - '@changesets/assemble-release-plan'
  - '@changesets/changelog-git'
  - '@changesets/changelog-github'
  - '@changesets/cli'
  - '@changesets/config'
  - '@changesets/errors'
  - '@changesets/get-dependents-graph'
  - '@changesets/get-github-info'
  - '@changesets/get-release-plan'
  - '@changesets/get-version-range-type'
  - '@changesets/git'
  - '@changesets/logger'
  - '@changesets/parse'
  - '@changesets/pre'
  - '@changesets/read'
  - '@changesets/should-skip-package'
  - '@changesets/types'
  - '@changesets/write'
  - '@cspotcode/source-map-support'
  - '@csstools/color-helpers'
  - '@csstools/css-calc'
  - '@csstools/css-color-parser'
  - '@csstools/css-parser-algorithms'
  - '@csstools/css-tokenizer'
  - '@esbuild/linux-x64'
  - '@eslint-community/eslint-utils'
  - '@eslint-community/regexpp'
  - '@eslint/eslintrc'
  - '@eslint/js'
  - '@gitbeaker/core'
  - '@gitbeaker/node'
  - '@gitbeaker/requester-utils'
  - '@humanwhocodes/config-array'
  - '@humanwhocodes/module-importer'
  - '@humanwhocodes/object-schema'
  - '@isaacs/cliui'
  - '@istanbuljs/schema'
  - '@jridgewell/gen-mapping'
  - '@jridgewell/resolve-uri'
  - '@jridgewell/set-array'
  - '@jridgewell/source-map'
  - '@jridgewell/sourcemap-codec'
  - '@jridgewell/trace-mapping'
  - '@manypkg/find-root'
  - '@manypkg/get-packages'
  - '@next/eslint-plugin-next'
  - '@nodelib/fs.scandir'
  - '@nodelib/fs.stat'
  - '@nodelib/fs.walk'
  - '@nolyfill/is-core-module'
  - '@octokit/auth-token'
  - '@octokit/core'
  - '@octokit/endpoint'
  - '@octokit/graphql'
  - '@octokit/openapi-types'
  - '@octokit/plugin-paginate-rest'
  - '@octokit/plugin-request-log'
  - '@octokit/plugin-rest-endpoint-methods'
  - '@octokit/request'
  - '@octokit/request-error'
  - '@octokit/rest'
  - '@octokit/types'
  - '@parcel/watcher'
  - '@pkgjs/parseargs'
  - '@pkgr/core'
  - '@polka/url'
  - '@rollup/plugin-inject'
  - '@rollup/pluginutils'
  - '@rollup/rollup-linux-x64-gnu'
  - '@rollup/rollup-linux-x64-musl'
  - '@rtsao/scc'
  - '@rushstack/eslint-patch'
  - '@sentry/cli'
  - '@sindresorhus/is'
  - '@sveltejs/acorn-typescript'
  - '@sveltejs/kit'
  - '@swc/core'
  - '@swc/core-linux-x64-gnu'
  - '@swc/core-linux-x64-musl'
  - '@swc/counter'
  - '@swc/helpers'
  - '@swc/types'
  - '@szmarczak/http-timer'
  - '@tootallnate/once'
  - '@trivago/prettier-plugin-sort-imports'
  - '@tsconfig/node10'
  - '@tsconfig/node12'
  - '@tsconfig/node14'
  - '@tsconfig/node16'
  - '@types/cacheable-request'
  - '@types/estree'
  - '@types/http-cache-semantics'
  - '@types/json-schema'
  - '@types/json5'
  - '@types/keyv'
  - '@types/node'
  - '@types/prop-types'
  - '@types/react'
  - '@types/responselike'
  - '@types/semver'
  - '@typescript-eslint/eslint-plugin'
  - '@typescript-eslint/parser'
  - '@typescript-eslint/scope-manager'
  - '@typescript-eslint/type-utils'
  - '@typescript-eslint/types'
  - '@typescript-eslint/typescript-estree'
  - '@typescript-eslint/utils'
  - '@typescript-eslint/visitor-keys'
  - '@ungap/structured-clone'
  - '@unrs/rspack-resolver-binding-linux-x64-gnu'
  - '@unrs/rspack-resolver-binding-linux-x64-musl'
  - '@vitest/coverage-v8'
  - '@vitest/expect'
  - '@vitest/mocker'
  - '@vitest/pretty-format'
  - '@vitest/runner'
  - '@vitest/snapshot'
  - '@vitest/spy'
  - '@vitest/ui'
  - '@vitest/utils'
  - '@vue/compiler-core'
  - '@vue/compiler-dom'
  - '@vue/compiler-sfc'
  - '@vue/compiler-ssr'
  - '@vue/shared'
  - acorn
  - acorn-jsx
  - acorn-walk
  - agent-base
  - ajv
  - ansi-colors
  - ansi-regex
  - ansi-styles
  - arg
  - argparse
  - aria-query
  - array-buffer-byte-length
  - array-includes
  - array-union
  - array.prototype.findlast
  - array.prototype.findlastindex
  - array.prototype.flat
  - array.prototype.flatmap
  - array.prototype.tosorted
  - arraybuffer.prototype.slice
  - asn1.js
  - assert
  - assertion-error
  - ast-types-flow
  - async-function
  - async-ref
  - async-retry
  - asynckit
  - atomic-sleep
  - available-typed-arrays
  - axe-core
  - axobject-query
  - balanced-match
  - base64-js
  - before-after-hook
  - better-path-resolve
  - bigint-buffer
  - blake-hash
  - bn.js
  - brace-expansion
  - braces
  - brorand
  - browser-resolve
  - browserify-aes
  - browserify-cipher
  - browserify-des
  - browserify-rsa
  - browserify-sign
  - browserify-zlib
  - buffer
  - buffer-equal-constant-time
  - buffer-from
  - buffer-xor
  - bufferutil
  - builtin-status-codes
  - cac
  - cacheable-lookup
  - cacheable-request
  - call-bind
  - call-bind-apply-helpers
  - call-bound
  - callsites
  - chai
  - chalk
  - chardet
  - check-error
  - ci-info
  - cipher-base
  - clone-response
  - clsx
  - color-convert
  - color-name
  - colors
  - combined-stream
  - commander
  - concat-map
  - console-browserify
  - constants-browserify
  - core-js
  - core-util-is
  - create-ecdh
  - create-hash
  - create-hmac
  - create-require
  - cross-spawn
  - crypto-browserify
  - cssesc
  - cssstyle
  - csstype
  - damerau-levenshtein
  - danger
  - data-urls
  - data-view-buffer
  - data-view-byte-length
  - data-view-byte-offset
  - dataloader
  - debug
  - decimal.js
  - decode-uri-component
  - decompress-response
  - deep-eql
  - deep-is
  - defer-to-connect
  - define-data-property
  - define-properties
  - delay
  - delayed-stream
  - deprecation
  - des.js
  - detect-indent
  - detect-libc
  - diff
  - diffie-hellman
  - dir-glob
  - doctrine
  - domain-browser
  - dotenv
  - dunder-proto
  - duplexify
  - eastasianwidth
  - ecdsa-sig-formatter
  - elliptic
  - emoji-regex
  - end-of-stream
  - enquirer
  - entities
  - es-abstract
  - es-define-property
  - es-errors
  - es-iterator-helpers
  - es-module-lexer
  - es-object-atoms
  - es-set-tostringtag
  - es-shim-unscopables
  - es-to-primitive
  - esbuild
  - escape-string-regexp
  - eslint
  - eslint-compat-utils
  - eslint-config-next
  - eslint-config-prettier
  - eslint-import-resolver-node
  - eslint-import-resolver-typescript
  - eslint-module-utils
  - eslint-plugin-import
  - eslint-plugin-jsx-a11y
  - eslint-plugin-lit
  - eslint-plugin-prettier
  - eslint-plugin-react
  - eslint-plugin-react-hooks
  - eslint-plugin-require-extensions
  - eslint-plugin-svelte
  - eslint-plugin-wc
  - eslint-scope
  - eslint-visitor-keys
  - esm-env
  - espree
  - esprima
  - esquery
  - esrap
  - esrecurse
  - estraverse
  - estree-walker
  - esutils
  - events
  - evp_bytestokey
  - expand-tilde
  - expect-type
  - extend-shallow
  - extendable-error
  - external-editor
  - fast-deep-equal
  - fast-diff
  - fast-glob
  - fast-json-patch
  - fast-json-stable-stringify
  - fast-levenshtein
  - fast-redact
  - fastq
  - fdir
  - fflate
  - file-entry-cache
  - fill-range
  - filter-obj
  - find-up
  - flag
  - flat-cache
  - flatted
  - for-each
  - foreground-child
  - form-data
  - fs-exists-sync
  - fs-extra
  - fs.realpath
  - function-bind
  - function.prototype.name
  - functions-have-names
  - get-intrinsic
  - get-proto
  - get-stdin
  - get-stream
  - get-symbol-description
  - get-tsconfig
  - git-config-path
  - glob
  - glob-parent
  - globals
  - globalthis
  - globby
  - gopd
  - got
  - graceful-fs
  - graphemer
  - happy-dom
  - has-bigints
  - has-flag
  - has-property-descriptors
  - has-proto
  - has-symbols
  - has-tostringtag
  - hash-base
  - hash.js
  - hasown
  - hmac-drbg
  - homedir-polyfill
  - html-encoding-sniffer
  - html-escaper
  - http-cache-semantics
  - http-proxy-agent
  - http2-wrapper
  - https-browserify
  - https-proxy-agent
  - human-id
  - husky
  - hyperlinker
  - iconv-lite
  - ieee754
  - ignore
  - import-fresh
  - imurmurhash
  - inflight
  - inherits
  - ini
  - internal-slot
  - is-arguments
  - is-array-buffer
  - is-async-function
  - is-bigint
  - is-boolean-object
  - is-bun-module
  - is-callable
  - is-core-module
  - is-data-view
  - is-date-object
  - is-extendable
  - is-extglob
  - is-finalizationregistry
  - is-fullwidth-code-point
  - is-generator-function
  - is-glob
  - is-map
  - is-nan
  - is-number
  - is-number-object
  - is-path-inside
  - is-plain-object
  - is-potential-custom-element-name
  - is-reference
  - is-regex
  - is-set
  - is-shared-array-buffer
  - is-string
  - is-subdir
  - is-symbol
  - is-typed-array
  - is-valid-element-name
  - is-weakmap
  - is-weakref
  - is-weakset
  - is-windows
  - isarray
  - isexe
  - isomorphic-timers-promises
  - istanbul-lib-coverage
  - istanbul-lib-report
  - istanbul-lib-source-maps
  - istanbul-reports
  - iterator.prototype
  - jackspeak
  - javascript-natural-sort
  - js-levenshtein-esm
  - js-tokens
  - js-yaml
  - jsdom
  - jsesc
  - json-buffer
  - json-schema-traverse
  - json-stable-stringify-without-jsonify
  - json5
  - jsonfile
  - jsonpointer
  - jsonwebtoken
  - jsx-ast-utils
  - jwa
  - jws
  - keccak
  - keyv
  - known-css-properties
  - language-subtag-registry
  - language-tags
  - levn
  - li
  - lightningcss
  - lightningcss-linux-x64-gnu
  - lightningcss-linux-x64-musl
  - lilconfig
  - lmdb
  - locate-character
  - locate-path
  - lodash
  - lodash.find
  - lodash.includes
  - lodash.isboolean
  - lodash.isinteger
  - lodash.isnumber
  - lodash.isobject
  - lodash.isplainobject
  - lodash.isstring
  - lodash.keys
  - lodash.mapvalues
  - lodash.memoize
  - lodash.merge
  - lodash.once
  - lodash.startcase
  - loose-envify
  - loupe
  - lowercase-keys
  - lru-cache
  - magic-string
  - magicast
  - make-dir
  - make-error
  - math-intrinsics
  - md5.js
  - memfs-or-file-map-to-github-branch
  - merge2
  - micromatch
  - miller-rabin
  - mime
  - mime-db
  - mime-types
  - mimic-response
  - minimalistic-assert
  - minimalistic-crypto-utils
  - minimatch
  - minimist
  - minipass
  - mri
  - mrmime
  - ms
  - msgpackr-extract
  - nanoid
  - natural-compare
  - node-cleanup
  - node-fetch
  - node-gyp-build
  - node-stdlib-browser
  - normalize-url
  - nwsapi
  - object-assign
  - object-inspect
  - object-is
  - object-keys
  - object.assign
  - object.entries
  - object.fromentries
  - object.groupby
  - object.values
  - on-exit-leak-free
  - once
  - optionator
  - os-browserify
  - os-tmpdir
  - outdent
  - override-require
  - own-keys
  - p-cancelable
  - p-filter
  - p-limit
  - p-locate
  - p-map
  - p-try
  - package-json-from-dist
  - package-manager-detector
  - pako
  - parent-module
  - parse-asn1
  - parse-diff
  - parse-git-config
  - parse-github-url
  - parse-link-header
  - parse-passwd
  - parse5
  - parse5-htmlparser2-tree-adapter
  - path-browserify
  - path-exists
  - path-is-absolute
  - path-key
  - path-parse
  - path-scurry
  - path-type
  - pathe
  - pathval
  - pbkdf2
  - picocolors
  - picomatch
  - pify
  - pino
  - pino-abstract-transport
  - pino-std-serializers
  - pinpoint
  - pkg-dir
  - possible-typed-array-names
  - postcss
  - postcss-load-config
  - postcss-safe-parser
  - postcss-scss
  - postcss-selector-parser
  - prelude-ls
  - prettier
  - prettier-linter-helpers
  - prettyjson
  - process
  - process-nextick-args
  - process-warning
  - prop-types
  - protobufjs
  - psl
  - public-encrypt
  - pump
  - punycode
  - qs
  - quansync
  - query-string
  - querystring-es3
  - querystringify
  - queue-microtask
  - quick-format-unescaped
  - quick-lru
  - randombytes
  - randomfill
  - react
  - react-is
  - read-yaml-file
  - readable-stream
  - readline-sync
  - real-require
  - reflect.getprototypeof
  - regenerator-runtime
  - regexp.prototype.flags
  - require-from-string
  - requireindex
  - requires-port
  - resolve
  - resolve-alpn
  - resolve-from
  - resolve-pkg-maps
  - responselike
  - retry
  - reusify
  - rimraf
  - ripemd160
  - rollup
  - rrweb-cssom
  - rspack-resolver
  - run-parallel
  - safe-array-concat
  - safe-buffer
  - safe-push-apply
  - safe-regex-test
  - safe-stable-stringify
  - safer-buffer
  - saxes
  - secp256k1
  - semver
  - set-function-length
  - set-function-name
  - set-proto
  - setimmediate
  - sha.js
  - sharp
  - shebang-command
  - shebang-regex
  - side-channel
  - side-channel-list
  - side-channel-map
  - side-channel-weakmap
  - siginfo
  - signal-exit
  - sirv
  - slash
  - sonic-boom
  - source-map
  - source-map-js
  - source-map-support
  - spawndamnit
  - split-on-first
  - split2
  - sprintf-js
  - stable-hash
  - stackback
  - std-env
  - stream-browserify
  - stream-http
  - stream-shift
  - strict-uri-encode
  - string-width
  - string.prototype.includes
  - string.prototype.matchall
  - string.prototype.repeat
  - string.prototype.trim
  - string.prototype.trimend
  - string.prototype.trimstart
  - string_decoder
  - strip-ansi
  - strip-bom
  - strip-json-comments
  - supports-color
  - supports-hyperlinks
  - supports-preserve-symlinks-flag
  - svelte
  - svelte-eslint-parser
  - svelte-preprocess
  - symbol-tree
  - synckit
  - term-size
  - terser
  - test-exclude
  - text-table
  - thread-stream
  - timers-browserify
  - tiny-secp256k1
  - tinybench
  - tinyexec
  - tinyglobby
  - tinypool
  - tinyrainbow
  - tinyspy
  - tmp
  - to-regex-range
  - totalist
  - tough-cookie
  - tr46
  - ts-api-utils
  - ts-node
  - tsconfig-paths
  - tslib
  - tty-browserify
  - turbo
  - turbo-linux-64
  - type-check
  - type-fest
  - typed-array-buffer
  - typed-array-byte-length
  - typed-array-byte-offset
  - typed-array-length
  - typescript
  - unbox-primitive
  - undici-types
  - unicorn-magic
  - universal-user-agent
  - universalify
  - uri-js
  - url
  - url-parse
  - usb
  - utf-8-validate
  - util
  - util-deprecate
  - v8-compile-cache-lib
  - vite
  - vite-node
  - vite-plugin-node-polyfills
  - vitest
  - vm-browserify
  - vue-demi
  - w3c-xmlserializer
  - webidl-conversions
  - whatwg-encoding
  - whatwg-mimetype
  - whatwg-url
  - which
  - which-boxed-primitive
  - which-builtin-type
  - which-collection
  - which-typed-array
  - why-is-node-running
  - word-wrap
  - workerd
  - wrap-ansi
  - wrappy
  - ws
  - xcase
  - xml-name-validator
  - xmlchars
  - xtend
  - yaml
  - yn
  - yocto-queue
  - zimmerframe
