packages:
  - 'packages/adapters/*'
  - 'packages/appkit'
  # - 'packages/appkit-new'
  - 'packages/common'
  - 'packages/ui'
  # - 'packages/ui-new'
  - 'packages/core'
  - 'packages/appkit-utils'
  - 'packages/scaffold-ui'
  # - 'packages/scaffold-ui-new'
  - 'packages/polyfills'
  - 'packages/wallet'
  - 'packages/siwe'
  - 'packages/siwx'
  - 'packages/wallet-button'
  - 'packages/cdn'
  - 'packages/experimental'
  - 'packages/cli'
  - 'apps/*'
  - '!apps/gallery-new'
  - '!apps/laboratory-new'
  - 'examples/*'
  - 'services/*'
