/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ConnectButton {
        "label": string;
    }
}
declare global {
    interface HTMLConnectButtonElement extends Components.ConnectButton, HTMLStencilElement {
    }
    var HTMLConnectButtonElement: {
        prototype: HTMLConnectButtonElement;
        new (): HTMLConnectButtonElement;
    };
    interface HTMLElementTagNameMap {
        "connect-button": HTMLConnectButtonElement;
    }
}
declare namespace LocalJSX {
    interface ConnectButton {
        "label"?: string;
    }
    interface IntrinsicElements {
        "connect-button": ConnectButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "connect-button": LocalJSX.ConnectButton & JSXBase.HTMLAttributes<HTMLConnectButtonElement>;
        }
    }
}
