/**
 * WARNING
 * The `w3m-modal` component will be imported dynamically in the Scaffold's client code.
 * That's why it requires it's own path to be imported that separately. To do this, we are creating sub-exports for the `w3m-modal` component specifically.
 * Make sure you're not exporting w3m-modal here.
 */

// -- Modal Components ---------------------------------- //
export * from '../src/modal/w3m-account-button/index.js'
export * from '../src/modal/w3m-button/index.js'
export * from '../src/modal/w3m-connect-button/index.js'
export * from '../src/modal/w3m-network-button/index.js'
export * from '../src/modal/w3m-router/index.js'
export * from '../src/modal/w3m-onramp-widget/index.js'

// -- Views --------------------------------------------- //
export * from '../src/views/w3m-account-settings-view/index.js'
export * from '../src/views/w3m-account-view/index.js'
export * from '../src/views/w3m-all-wallets-view/index.js'
export * from '../src/views/w3m-buy-in-progress-view/index.js'
export * from '../src/views/w3m-connect-view/index.js'
export * from '../src/views/w3m-connecting-external-view/index.js'
export * from '../src/views/w3m-connecting-multi-chain-view/index.js'
export * from '../src/views/w3m-connecting-wc-view/index.js'
export * from '../src/views/w3m-choose-account-name-view/index.js'
export * from '../src/views/w3m-downloads-view/index.js'
export * from '../src/views/w3m-get-wallet-view/index.js'
export * from '../src/views/w3m-register-account-name-view/index.js'
export * from '../src/views/w3m-register-account-name-success-view/index.js'
export * from '../src/views/w3m-network-switch-view/index.js'
export * from '../src/views/w3m-networks-view/index.js'
export * from '../src/views/w3m-onramp-activity-view/index.js'
export * from '../src/views/w3m-onramp-fiat-select-view/index.js'
export * from '../src/views/w3m-onramp-providers-view/index.js'
export * from '../src/views/w3m-onramp-tokens-select-view/index.js'
export * from '../src/views/w3m-swap-view/index.js'
export * from '../src/views/w3m-switch-active-chain-view/index.js'
export * from '../src/views/w3m-swap-preview-view/index.js'
export * from '../src/views/w3m-swap-select-token-view/index.js'
export * from '../src/views/w3m-swap-view/index.js'
export * from '../src/views/w3m-transactions-view/index.js'
export * from '../src/views/w3m-what-is-a-network-view/index.js'
export * from '../src/views/w3m-what-is-a-wallet-view/index.js'
export * from '../src/views/w3m-what-is-a-buy-view/index.js'
export * from '../src/views/w3m-email-verify-otp-view/index.js'
export * from '../src/views/w3m-email-verify-device-view/index.js'
export * from '../src/views/w3m-approve-transaction-view/index.js'
export * from '../src/views/w3m-upgrade-wallet-view/index.js'
export * from '../src/views/w3m-upgrade-to-smart-account-view/index.js'
export * from '../src/views/w3m-update-email-wallet-view/index.js'
export * from '../src/views/w3m-update-email-primary-otp-view/index.js'
export * from '../src/views/w3m-update-email-secondary-otp-view/index.js'
export * from '../src/views/w3m-unsupported-chain-view/index.js'
export * from '../src/views/w3m-wallet-receive-view/index.js'
export * from '../src/views/w3m-wallet-compatible-networks-view/index.js'
export * from '../src/views/w3m-wallet-send-view/index.js'
export * from '../src/views/w3m-wallet-send-select-token-view/index.js'
export * from '../src/views/w3m-wallet-send-preview-view/index.js'
export * from '../src/views/w3m-connect-wallets-view/index.js'
export * from '../src/views/w3m-connect-socials-view/index.js'
export * from '../src/views/w3m-connecting-social-view/index.js'
export * from '../src/views/w3m-profile-view/index.js'
export * from '../src/views/w3m-switch-address-view/index.js'
export * from '../src/views/w3m-connecting-farcaster-view/index.js'

// -- Partials ------------------------------------------ //
export * from '../src/partials/w3m-all-wallets-list/index.js'
export * from '../src/partials/w3m-all-wallets-list-item/index.js'
export * from '../src/partials/w3m-all-wallets-search/index.js'
export * from '../src/partials/w3m-connecting-header/index.js'
export * from '../src/partials/w3m-connecting-wc-browser/index.js'
export * from '../src/partials/w3m-connecting-wc-desktop/index.js'
export * from '../src/partials/w3m-connecting-wc-mobile/index.js'
export * from '../src/partials/w3m-connecting-wc-qrcode/index.js'
export * from '../src/partials/w3m-connecting-wc-unsupported/index.js'
export * from '../src/partials/w3m-connecting-wc-web/index.js'
export * from '../src/partials/w3m-swap-details/index.js'
export * from '../src/partials/w3m-swap-input/index.js'
export * from '../src/partials/w3m-swap-input-skeleton/index.js'
export * from '../src/partials/w3m-header/index.js'
export * from '../src/partials/w3m-help-widget/index.js'
export * from '../src/partials/w3m-onramp-activity-item/index.js'
export * from '../src/partials/w3m-onramp-input/index.js'
export * from '../src/partials/w3m-onramp-provider-item/index.js'
export * from '../src/partials/w3m-legal-footer/index.js'
export * from '../src/partials/w3m-mobile-download-links/index.js'
export * from '../src/partials/w3m-onramp-providers-footer/index.js'
export * from '../src/partials/w3m-snackbar/index.js'
export * from '../src/partials/w3m-email-login-widget/index.js'
export * from '../src/partials/w3m-account-default-widget/index.js'
export * from '../src/partials/w3m-account-wallet-features-widget/index.js'
export * from '../src/partials/w3m-account-activity-widget/index.js'
export * from '../src/partials/w3m-account-nfts-widget/index.js'
export * from '../src/partials/w3m-account-tokens-widget/index.js'
export * from '../src/partials/w3m-activity-list/index.js'
export * from '../src/partials/w3m-input-token/index.js'
export * from '../src/partials/w3m-input-address/index.js'
export * from '../src/partials/w3m-wallet-send-details/index.js'
export * from '../src/partials/w3m-tooltip/index.js'
export * from '../src/partials/w3m-tooltip-trigger/index.js'
export * from '../src/partials/w3m-social-login-widget/index.js'
export * from '../src/partials/w3m-wallet-login-list/index.js'
export * from '../src/partials/w3m-social-login-list/index.js'
export * from '../src/partials/w3m-connect-announced-widget/index.js'
export * from '../src/partials/w3m-connect-custom-widget/index.js'
export * from '../src/partials/w3m-connect-featured-widget/index.js'
export * from '../src/partials/w3m-connect-injected-widget/index.js'
export * from '../src/partials/w3m-connect-multi-chain-widget/index.js'
export * from '../src/partials/w3m-connect-external-widget/index.js'
export * from '../src/partials/w3m-connect-recent-widget/index.js'
export * from '../src/partials/w3m-connect-recommended-widget/index.js'
export * from '../src/partials/w3m-connect-walletconnect-widget/index.js'
export * from '../src/partials/w3m-connector-list/index.js'
export * from '../src/partials/w3m-all-wallets-widget/index.js'
export * from '../src/partials/w3m-account-auth-button/index.js'
