import type { Metadata } from 'next'
import { Inter as interFonts } from 'next/font/google'
import './globals.css'
import ContextProvider from '@/context'

const inter = interFonts({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ContextProvider>{children}</ContextProvider>
      </body>
    </html>
  )
}
