import '@reown/appkit-controllers'

declare module '@reown/appkit-controllers' {
  interface RouterControllerState {
    view:
      | 'Account'
      | 'AccountSettings'
      | 'AllWallets'
      | 'ApproveTransaction'
      | 'BuyInProgress'
      | 'WalletCompatibleNetworks'
      | 'ChooseAccountName'
      | 'Connect'
      | 'Create'
      | 'ConnectingExternal'
      | 'ConnectingFarcaster'
      | 'ConnectingWalletConnect'
      | 'ConnectingWalletConnectBasic'
      | 'ConnectingSiwe'
      | 'ConnectingSocial'
      | 'ConnectSocials'
      | 'ConnectWallets'
      | 'Downloads'
      | 'EmailVerifyOtp'
      | 'EmailVerifyDevice'
      | 'GetWallet'
      | 'Networks'
      | 'OnRampActivity'
      | 'OnRampFiatSelect'
      | 'OnRampProviders'
      | 'OnRampTokenSelect'
      | 'Profile'
      | 'RegisterAccountName'
      | 'RegisterAccountNameSuccess'
      | 'SwitchNetwork'
      | 'SwitchAddress'
      | 'Transactions'
      | 'UnsupportedChain'
      | 'UpdateEmailWallet'
      | 'UpdateEmailPrimaryOtp'
      | 'UpdateEmailSecondaryOtp'
      | 'UpgradeEmailWallet'
      | 'WalletReceive'
      | 'WalletSend'
      | 'WalletSendPreview'
      | 'WalletSendSelectToken'
      | 'WhatIsANetwork'
      | 'WhatIsAWallet'
      | 'WhatIsABuy'
      | 'Swap'
      | 'SwapSelectToken'
      | 'SwapPreview'
      | 'ConnectingMultiChain'
      | 'SwitchActiveChain'
      | 'SmartSessionCreated'
      | 'SmartSessionList'
      | 'SIWXSignMessage'
      | 'Pay'
      | 'PayLoading'
  }
}
