export type RouterView =
  | 'CoinbaseExtensionConnector'
  | 'CoinbaseMobileConnector'
  | 'ConnectWallet'
  | 'GetWallet'
  | 'InjectedConnector'
  | 'LedgerDesktopConnector'
  | 'MetaMaskConnector'
  | 'SelectNetwork'
  | 'WalletConnectConnector'
  | 'Account'
