name: UI Tests

on:
  workflow_call:
    inputs:
      branch:
        description: 'The branch to use'
        default: 'main'
        required: false
        type: string
      wallet-url:
        description: 'The wallet url'
        default: 'https://react-wallet.walletconnect.com/'
        required: false
        type: string

jobs:
  ui_tests_demo_app:
    name: 'Playwright Tests'
    runs-on: [self-hosted, aws-ecs-16cpu-64mem-30m]
    strategy:
      fail-fast: false
    timeout-minutes: 20
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          repository: reown-com/appkit
          ref: ${{ inputs.branch }}

      - uses: pnpm/action-setup@v4
        name: Install pnpm

      - name: setup-node
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'pnpm'

      - name: Install dependencies # Install again to link binaries, etc.
        run: pnpm install

      - name: Install Playwright Browsers
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        working-directory: ./apps/laboratory/
        run: pnpm playwright:install

      - name: Wait for Vercel Preview URL
        uses: UnlyEd/github-action-await-vercel@v2.0
        id: await-vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        with:
          deployment-url: demo.reown.com # TODO Replace by the domain you want to test
          timeout: 10 # Wait for 10 seconds before failing
          poll-interval: 1 # Wait for 1 second before each retry

      - name: Display deployment status
        run: 'echo The deployment at ${{ fromJson(steps.await-vercel.outputs.deploymentDetails).url }} is ${{ fromJson(steps.await-vercel.outputs.deploymentDetails).readyState }}'

      - name: Run Playwright tests
        env:
          BASE_URL: https://${{ fromJson(steps.await-vercel.outputs.deploymentDetails).url }}/
          CI: true
        working-directory: ./apps/demo/
        run: pnpm playwright:test

      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: playwright-report-${{ matrix.shard }}
          path: ./apps/demo/playwright-report/
          retention-days: 7
