name: Unified dependency update (pnpm workspace)

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 6 * * 1' # every Monday 06:00 UTC

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: unified-deps
  cancel-in-progress: false

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.5.0

      - name: Install deps
        run: pnpm install --no-frozen-lockfile

      - name: Update all workspace deps to latest
        run: pnpm up -r -L

      - name: Format
        run: pnpm prettier:format || true

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore(deps): unified workspace dependency update'
          title: 'chore(deps): unified workspace dependency update'
          body: |
            Automated unified dependency update across the pnpm workspace.

            - Bumps all workspace dependencies using `pnpm up -r -L`.
            - Runs formatting via `pnpm prettier:format`.

            This replaces many small dependency PRs with a single, easy-to-review PR.
          branch: chore/unified-deps
          labels: |
            dependencies
            chore
          delete-branch: true
          signoff: false
          add-paths: |
            **/package.json
            pnpm-lock.yaml
